/* NativeMath.java
 *
 * Single-file solution: contains Java code + the native C implementation (in this comment)
 * Steps to build and run are included below.
 *
 * ----------------------------------------------------------------------
 * C code for the native DLL (copy everything between the START/END markers
 * into a file named NativeMath.c and compile with Visual C++):
 * ----------------------------------------------------------------------
 *
 * // ---------- START NativeMath.c ----------
 * #include <jni.h>
 * #include "NativeMath.h"   // generated by `javac -h . NativeMath.java` OR you can forward declare
 * #include <math.h>
 *
 * // If you don't generate header, use forward declarations like:
 * // JNIEXPORT jint JNICALL Java_NativeMath_add(JNIEnv *, jobject, jint, jint);
 * // (but using javac -h is recommended)
 *
 * JNIEXPORT jint JNICALL Java_NativeMath_add(JNIEnv *env, jobject obj, jint a, jint b) {
 *     return a + b;
 * }
 *
 * JNIEXPORT jint JNICALL Java_NativeMath_sub(JNIEnv *env, jobject obj, jint a, jint b) {
 *     return a - b;
 * }
 *
 * JNIEXPORT jint JNICALL Java_NativeMath_mul(JNIEnv *env, jobject obj, jint a, jint b) {
 *     return a * b;
 * }
 *
 * JNIEXPORT jdouble JNICALL Java_NativeMath_div(JNIEnv *env, jobject obj, jint a, jint b) {
 *     if (b == 0) {
 *         // throw ArithmeticException from native code
 *         jclass exc = (*env)->FindClass(env, "java/lang/ArithmeticException");
 *         if (exc != NULL) {
 *             (*env)->ThrowNew(env, exc, "Division by zero in native code");
 *         }
 *         return 0.0; // not reached if exception thrown
 *     }
 *     return ((jdouble)a) / ((jdouble)b);
 * }
 *
 * JNIEXPORT jlong JNICALL Java_NativeMath_gcd(JNIEnv *env, jobject obj, jlong a, jlong b) {
 *     long aa = a >= 0 ? a : -a;
 *     long bb = b >= 0 ? b : -b;
 *     while (bb != 0) {
 *         long t = aa % bb;
 *         aa = bb;
 *         bb = t;
 *     }
 *     return (jlong)aa;
 * }
 *
 * JNIEXPORT jdouble JNICALL Java_NativeMath_pow(JNIEnv *env, jobject obj, jdouble base, jdouble exp) {
 *     return pow(base, exp);
 * }
 *
 * // ---------- END NativeMath.c ----------
 *
 * ----------------------------------------------------------------------
 * Build instructions (Windows / Visual C++). See the README text after the Java code.
 * ----------------------------------------------------------------------
 */

public class NativeMath {
    // Native methods (these will be implemented in the DLL)
    public native int add(int a, int b);
    public native int sub(int a, int b);
    public native int mul(int a, int b);
    public native double div(int a, int b); // returns double
    public native long gcd(long a, long b);
    public native double pow(double base, double exp);

    // Load the native library. Name = NativeMath -> looks for NativeMath.dll on Windows
    static {
        try {
            System.loadLibrary("NativeMath");
        } catch (UnsatisfiedLinkError e) {
            System.err.println("Native library failed to load: " + e.getMessage());
            System.err.println("Make sure NativeMath.dll is on java.library.path (or in the same folder).");
            // Re-throw if you want the program to stop here:
            // throw e;
        }
    }

    // Test application
    public static void main(String[] args) {
        NativeMath nm = new NativeMath();

        // Basic integer math
        int a = 18, b = 4;
        System.out.println("a = " + a + ", b = " + b);
        System.out.println("add: " + nm.add(a, b));
        System.out.println("sub: " + nm.sub(a, b));
        System.out.println("mul: " + nm.mul(a, b));
        try {
            System.out.println("div: " + nm.div(a, b));
            System.out.println("div (by zero test): attempting division by zero...");
            nm.div(a, 0); // this should trigger an ArithmeticException thrown from native code
        } catch (ArithmeticException ex) {
            System.out.println("Caught ArithmeticException from native code: " + ex.getMessage());
        }

        // GCD
        long x = 270, y = 192;
        System.out.println("gcd(" + x + ", " + y + ") = " + nm.gcd(x, y));

        // Power
        double base = 2.5, exp = 3.0;
        System.out.println(base + " ^ " + exp + " = " + nm.pow(base, exp));
    }
}

/*
-----------------------------
How to build & run (Windows, Visual C++ CLI):
-----------------------------
1) Prerequisites:
   - Java JDK installed. Set JAVA_HOME to your JDK root.
   - Visual Studio / Visual C++ Build Tools (cl.exe) available in PATH (use "Developer Command Prompt").

2) Compile Java and generate JNI header:
   In a command prompt in the directory containing NativeMath.java:

   javac NativeMath.java
   javac -h . NativeMath.java

   The second command generates a header file named: NativeMath.h

   Note: If you prefer to not generate the header, you can forward-declare functions in C
   with the appropriate names — but using javac -h is recommended.

3) Create NativeMath.c
   Copy the C code from the top comment (between START/END NativeMath.c) into a file named:
   NativeMath.c

   If you used javac -h, the generated header NativeMath.h will contain proper JNI function signatures.

4) Compile the C code into a DLL using Visual C++:
   Open "Developer Command Prompt for VS" so cl.exe and linker are available, then:

   cl /LD NativeMath.c /I"%JAVA_HOME%\include" /I"%JAVA_HOME%\include\win32" /FeNativeMath.dll

   Explanation:
    - /LD : Create a DLL
    - /I include paths point to JNI headers inside the JDK
    - /FeNativeMath.dll sets the output filename

   If you generated NativeMath.h, make sure NativeMath.c includes it:
     #include "NativeMath.h"

5) Result:
   - You should now have NativeMath.dll (and possibly NativeMath.lib).
   - Make sure NativeMath.dll is either:
       * in the same directory where you run `java`, or
       * in a folder in your PATH, or
       * provide full path with System.load("C:\\path\\to\\NativeMath.dll") in the Java static block.

6) Run the Java test:
   java NativeMath

   Expected output (approx):
   a = 18, b = 4
   add: 22
   sub: 14
   mul: 72
   div: 4.5
   div (by zero test): attempting division by zero...
   Caught ArithmeticException from native code: Division by zero in native code
   gcd(270, 192) = 6
   2.5 ^ 3.0 = 15.625

Notes & troubleshooting:
- Make sure bitness matches: 64-bit JDK needs 64-bit DLL (compile with 64-bit toolset).
- If cl.exe complains, open the proper Visual Studio Developer Command Prompt.
- If `System.loadLibrary("NativeMath")` fails, try using System.load with absolute path or put the DLL on PATH.
- The native code throws a Java ArithmeticException for division by zero; that's optional — you could instead return INF/NaN.

If you want, I can also:
- Provide the exact `NativeMath.c` file content (ready to copy/paste).
- Provide adapted build commands for MinGW or Linux (shared object `.so`) instead of Windows DLL.
- Show how to generate and inspect the `NativeMath.h` header `javac -h . NativeMath.java`.
*/
